/-
# Cyclotomic Function Fields

This file defines cyclotomic function fields K(Λ_M) and proves their basic properties:
- CyclotomicField M: The field K(Λ_M)
- Finite dimensionality and degree formula: [K(Λ_M) : K] = q^(deg M)
- Separability: K(Λ_M)/K is separable
- Galois property: K(Λ_M)/K is Galois
- Abelian Galois group: Gal(K(Λ_M)/K) is abelian

Reference: Hayes (1974), Sections 4-6
-/

import CyclotomicFunctionFields.Carlitz.Torsion
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.LinearAlgebra.Dimension.Finrank

open Module

namespace CyclotomicFunctionFields

variable {q : ℕ} [Fact q.Prime]

/-- The cyclotomic function field K(Λ_M) generated by M-division points -/
def CyclotomicField (M : A q) (φ : CarlitzModule q) : IntermediateField (K q) (L q) :=
  IntermediateField.adjoin (K q) (DivisionPoints M φ)

namespace CyclotomicField

variable (M : A q) (φ : CarlitzModule q)

/-- K(Λ_M)/K is finite dimensional -/
theorem finite_dimensional (hM : M ≠ 0) :
  FiniteDimensional (K q) (CyclotomicField M φ) := sorry

/-- The degree [K(Λ_M) : K] equals q^(deg M) -/
theorem degree (hM : M ≠ 0) :
  finrank (K q) (CyclotomicField M φ) = q ^ Polynomial.natDegree M := sorry

/-- K(Λ_M)/K is separable -/
theorem isSeparable (hM : M ≠ 0) :
  Algebra.IsSeparable (K q) (CyclotomicField M φ) := sorry

/-- K(Λ_M)/K is Galois -/
theorem isGalois (hM : M ≠ 0) :
  IsGalois (K q) (CyclotomicField M φ) := sorry

/-- The Galois group Gal(K(Λ_M)/K) is abelian -/
theorem galoisGroup_abelian (hM : M ≠ 0) :
  ∀ σ τ : (CyclotomicField M φ) ≃ₐ[K q] (CyclotomicField M φ), σ * τ = τ * σ := sorry

/-- Tower property for cyclotomic fields -/
theorem tower {M N : A q} (hM : M ≠ 0) (hN : N ≠ 0) (h : M ∣ N) :
  (CyclotomicField M φ : Set (L q)) ⊆ (CyclotomicField N φ : Set (L q)) := sorry

end CyclotomicField

end CyclotomicFunctionFields
